### PR TITLE
feat: Add meta properties for application specific console paths

### PR DESCRIPTION
**Pull request by carloslubbers**
This pr will allow the user to set env properties for console paths per application, overriding the default search paths of CONSOLE_FOLDER.

Setting for example DSTABILITY_CONSOLE_FOLDER to "C:\Program Files (x86)\Deltares\D-GEO Suite\D-Stability 2023.01\bin\D-Stability Console.exe" will let GEOLib use the system installed version of D-Stability without requiring a local copy in the CONSOLE_FOLDER

### CODE REVIEW

**Comment by MatthiasHauthDeltares** [comment]
I tried the following:
```python
from pathlib import Path

from geolib import DStabilityModel

_path_stix = Path(r"C:\Users\hauth\.....\abc.stix")
model = DStabilityModel()
model.serialize(_path_stix)
print(model.custom_console_path)  # returns None
model.custom_console_path = r"C:\Program Files (x86)\Deltares\D-GEO Suite\D-Stability 2024.01\bin"  # Value error

```
It returns the error below. How can i manually set the console path?

Traceback (most recent call last):
  File "C:\Users\hauth\bitbucket\GEOLib\tests\qwer.py", line 9, in <module>
    model.custom_console_path = r"C:\Program Files (x86)\Deltares\D-GEO Suite\D-Stability 2024.01\bin"
  File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "DStabilityModel" object has no field "custom_console_path"

**Comment by carloslubbers** [comment]
@MatthiasHauthDeltares The custom_console_path is an evaluated property so cannot be set directly, the value is retrieved from the meta properties (or from the geolib.env file) DSTABILITY_CONSOLE_PATH. Can you try setting that one?

**Comment by MatthiasHauthDeltares** [comment]
I don't quite get how you set a meta property. I only see a method ```get_meta_property``` but no setter

**Comment by carloslubbers** [comment]
@MatthiasHauthDeltares Oops, the docs incorrectly specified there would be a meta property available on the model objects, I've added a set_meta_property for your convenience now:

from pathlib import Path

dm = DStabilityModel()
dm.set_meta_property("dstability_console_path", Path("C:/Program Files/......../DStabilityConsole.exe"))

Though note that meta properties are defined globally in your runtime and not per model, which is a bit ugly, so setting it on a model will change it for all models in your script

**Comment by carloslubbers** [comment]
This PR closes #149

**Comment by carloslubbers** [comment]
This PR closes #164

**Review by wfaustmann — APPROVED** [review]

**Pull request merged**
