### PR TITLE
Add dgeoflow

### PR DESCRIPTION
**Pull request by MatthiasHauthVIKTOR**
Hi all,

This is my proposition for the integration of the new version of D-Geoflow. It is mainly based on the existing code of D-Stability as the files structure will be similar. A few things to bear in mind:

- I only focus in this branch on generating the input files, I commented out everything related to the generation and parsing of the output. I will probably do the output later if I still have time/budget for it.
- I do not have access to D-Geoflow yet, so I could not test my scripts to check the validity and robustness of the generated input files. 
- The structure of the scenario.json might change in the near future?
- I didn't write any unit-tests yet, maybe for another Pull request?

### CODE REVIEW

**Comment by carloslubbers** [comment]
Thanks for the pull request, it would be nice to have support for the new D-Geo Flow product as soon as possible. I noticed you wrote in your description you do not have access to D-Geo Flow yet, we will be distributing a development version as part of the DSD-NL D-GEO User meeting on Wednesday, you can join this event (in Delft) to learn more (see: https://softwaredagen.deltares.nl/-/d-geo-gebruikersdag-2022?redirect=%2F) or keep an eye on our community website, we will probably post a download link there by Wednesday as well (https://oss.deltares.nl/web/embankment).

If possible it would be nice to have at least some basic unit tests as part of this pull request so we can more easily validate the proper functionality of your code!

If you need any help, please let me or the other repo maintainers know.

**Comment by MatthiasHauthVIKTOR** [comment]
I'll make sure that the pipeline passes and write a few standard unit-tests. As my Dutch is pretty basic, I don't think it will be particularly useful to join the event in person (I would have loved to though!). However, maybe I could download the presentation and have a look to the slides?

**Comment by carloslubbers** [comment]
You can find a download link to the development build of D-Geo Flow on our community website, we will be adding our presentation later. Feel free to check the included tutorial file for some guidance: https://oss.deltares.nl/web/embankment

**Comment by MatthiasHauthVIKTOR** [comment]
A bit of update:

- I managed to open a project in DGeoflow with the input files generated from this library and run calculations, so this is encouraging!
- I added a few tests for internal.py model.py and the parser.
- I don't really understand the errors thrown in the GitHub pipeline, but i could locally run `poetry run pytest`

**Comment by MatthiasHauthVIKTOR** [comment]
Hi Carlos, I thought it would be good to share with you that I will be leaving VIKTOR at the end of the month and I won't be able to work on this Pull request afterwards.

**Comment by carloslubbers** [comment]
Thanks for the heads-up. We will be taking over development of the d-geo flow model later in that case, thank you for the first efforts! Is there anything you plan to add to this PR before you leave? If not I will merge it into a feature branch on our end for future work

**Comment by MatthiasHauthVIKTOR** [comment]
There is nothing else I would like to add to this PR. Maybe we'll cross paths again as I will join Deltares next September ;)

**Pull request merged**
